### ISSUE TITLE
transfer_function_coef

### ISSUE THREAD

**Issue by DrFishWave** [lamfur07/Flight-Dynamics-and-Control-UAVs#1]

**Comment by TikhonovAleksey-AI** [comment]
transfer_function_coef not found

**Comment by lamfur07** [comment]
When you run the compute_tf_model.m .. in the end your saving your coefficients in the transfer_function_coef.mat which you load after

**Comment by lamfur07** [comment]
When you run the compute_tf_model.m .. in the end your saving your coefficients in the transfer_function_coef.mat which you load after
